"""Generate comprehensive multi-format dispute evidence samples.

Generates:
1. CSV files (dispute-ledger.csv, dispute-claims-batch.csv)
2. PDF files (chargeback-notice-RF01.pdf, bank-settlement-receipt.pdf)
3. PNG image files (upi-payment-receipt.png, delivery-confirmation-slip.png)
4. XLSX spreadsheet files (merchant-reconciliation-sheet.xlsx)
5. TXT files (customer-complaint-hinglish.txt, customer-complaint-hindi.txt)
6. JSON structured payloads (normal.json, hinglish.json, contradiction.json, adversarial.json, missing-evidence.json, ood.json)
7. manifest.json cataloging all evidence files
8. carve-sample-bundles.zip containing all the above multi-format files
"""

from __future__ import annotations

import io
import json
import zipfile
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

SAMPLES_DIR = Path("frontend/public/samples")
SAMPLES_DIR.mkdir(parents=True, exist_ok=True)


def generate_csv_samples() -> None:
    csv_ledger = (
        "transaction_id,payment_id,amount_inr,status,refund_status,refund_amount_inr,customer_note,city,bank,date\n"
        "TXN_849201,pay_2500_ok,2500.00,captured,processed,2500.00,Your INR 2500 refund was processed on 28 August,Bengaluru,HDFC Bank,2026-08-28\n"
        "TXN_849202,pay_3200_disp,3200.00,captured,none,,Aapka INR 3200 refund kal process ho gaya tha,Mumbai,ICICI Bank,2026-08-29\n"
        "TXN_849203,pay_500_dev,500.00,captured,none,,कृपया मेरा 500 रुपये का रिफंड वापस करो,Delhi,SBI,2026-08-30\n"
        "TXN_849204,pay_4999_rvw,4999.00,captured,none,,Debit of 4999 rupaye duplicate charged,Hyderabad,Axis Bank,2026-09-01\n"
    )
    (SAMPLES_DIR / "dispute-ledger.csv").write_text(csv_ledger, encoding="utf-8")

    csv_batch = (
        "claim_id,payment_id,customer_name,amount_inr,vpa_handle,bank_utr,dispute_reason,location\n"
        "RF-HI-01,pay_3200_disp,Rahul Sharma,3200.00,rahul@okhdfcbank,492019284719,refund_not_processed,Bengaluru\n"
        "RF-MH-02,pay_2500_ok,Pooja Patel,2500.00,pooja@oksbi,892019284102,refund_not_processed,Mumbai\n"
        "RF-DL-03,pay_500_dev,Amit Kumar,500.00,amit@okaxis,392019284991,refund_not_processed,Delhi\n"
    )
    (SAMPLES_DIR / "dispute-claims-batch.csv").write_text(csv_batch, encoding="utf-8")


def generate_txt_samples() -> None:
    txt_hinglish = (
        "Aapka INR 3,200 refund kal process ho gaya tha in Bengaluru via Razorpay to rahul@okhdfcbank, "
        "reference RF-HI-01, bank UTR 492019284719. Lekin abhi tak mere account mein credit nahi aaya hai. "
        "Please check karke amount wapas bhejo."
    )
    (SAMPLES_DIR / "customer-complaint-hinglish.txt").write_text(txt_hinglish, encoding="utf-8")

    txt_hindi = (
        "कृपया मेरा 500 रुपये का रिफंड वापस करो। मैंने 28 अगस्त को दिल्ली से ऑर्डर किया था। "
        "ट्रांजैक्शन आईडी pay_500_devanagari और बैंक स्टेट बैंक ऑफ इंडिया (SBI) है। "
        "पैसा दो बार कट गया था।"
    )
    (SAMPLES_DIR / "customer-complaint-hindi.txt").write_text(txt_hindi, encoding="utf-8")


def generate_pdf_document(
    filename: str,
    title: str,
    claim_id: str,
    customer_text: str,
    amount_inr: str,
    payment_id: str,
    bank_ref: str,
    status_text: str,
) -> None:
    # Generate clean, standards-compliant PDF 1.4 binary document
    lines = [
        "BT",
        "/F1 18 Tf",
        "50 780 Td",
        f"({title}) Tj",
        "/F1 10 Tf",
        "0 -30 Td",
        f"(Official Dispute Evidence Notice | Reference: {claim_id} | Issued: 2026-09-05) Tj",
        "0 -25 Td",
        f"(Customer Claim Statement: {customer_text[:90]}) Tj",
        "0 -15 Td",
        f"({customer_text[90:180]}) Tj" if len(customer_text) > 90 else "(Grounded in verified customer communication records) Tj",
        "0 -25 Td",
        f"(Claimed Amount: INR {amount_inr} | Payment ID: {payment_id}) Tj",
        "0 -18 Td",
        f"(Payment Rail / Bank Reference: {bank_ref}) Tj",
        "0 -18 Td",
        f"(Authoritative Ledger Truth: {status_text}) Tj",
        "0 -30 Td",
        "/F1 12 Tf",
        "(Cryptographic Evidence Verification: SHA-256 Digest Verified) Tj",
        "0 -20 Td",
        "/F1 8 Tf",
        "(Generated by PRAMAAN Dispute Integrity Gate - Defense-Only Evaluation) Tj",
        "ET",
    ]
    stream_content = "\n".join(lines).encode("latin1", errors="replace")

    objects = []
    # 1: Catalog
    objects.append(b"1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n")
    # 2: Pages
    objects.append(b"2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n")
    # 3: Page
    objects.append(
        b"3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595.28 841.89] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n"
    )
    # 4: Stream
    stream_obj = (
        f"4 0 obj\n<< /Length {len(stream_content)} >>\nstream\n".encode("latin1")
        + stream_content
        + b"\nendstream\nendobj\n"
    )
    objects.append(stream_obj)
    # 5: Font
    objects.append(
        b"5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n"
    )

    pdf_bytes = io.BytesIO()
    pdf_bytes.write(b"%PDF-1.4\n")
    offsets = []
    for obj in objects:
        offsets.append(pdf_bytes.tell())
        pdf_bytes.write(obj)

    xref_offset = pdf_bytes.tell()
    pdf_bytes.write(f"xref\n0 {len(objects) + 1}\n".encode("latin1"))
    pdf_bytes.write(b"0000000000 65535 f \n")
    for off in offsets:
        pdf_bytes.write(f"{off:010d} 00000 n \n".encode("latin1"))

    pdf_bytes.write(
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref_offset}\n%%EOF\n".encode(
            "latin1"
        )
    )

    (SAMPLES_DIR / filename).write_bytes(pdf_bytes.getvalue())


def generate_png_receipts() -> None:
    # 1. UPI Payment Receipt
    width, height = 640, 780
    img = Image.new("RGB", (width, height), color=(248, 249, 250))
    draw = ImageDraw.Draw(img)

    # Header bar
    draw.rectangle([(0, 0), (width, 100)], fill=(15, 23, 42))  # Dark slate
    draw.text((30, 35), "UPI Payment Receipt - Razorpay Ingestion", fill=(255, 255, 255))

    # Card background
    draw.rectangle([(30, 130), (width - 30, height - 40)], fill=(255, 255, 255), outline=(226, 232, 240), width=2)

    # Success tick badge
    draw.ellipse([(60, 160), (120, 220)], fill=(22, 163, 74))  # Emerald green
    draw.text((80, 178), "OK", fill=(255, 255, 255))

    draw.text((140, 165), "Payment Successful", fill=(15, 23, 42))
    draw.text((140, 190), "Transaction routed through NPCI UPI Rails", fill=(100, 116, 139))

    # Amount display
    draw.text((60, 250), "INR 3,200.00", fill=(15, 23, 42))
    draw.line([(60, 290), (width - 60, 290)], fill=(226, 232, 240), width=1)

    # Field rows
    fields = [
        ("Paid To", "Merchant Retail Store (merchant@okhdfcbank)"),
        ("Customer Handle", "rahul@okhdfcbank (Rahul Sharma)"),
        ("Dispute Reference", "RF-HI-01"),
        ("Payment ID", "pay_89a0bcdef123"),
        ("Bank UTR / RRN", "492019284719"),
        ("Origin Bank", "HDFC Bank (Bengaluru Hub)"),
        ("Transaction Date", "28 August 2026, 14:32:19 IST"),
        ("Gateway Status", "CAPTURED (No refund recorded in ledger)"),
    ]

    y = 310
    for label, val in fields:
        draw.text((60, y), label, fill=(100, 116, 139))
        draw.text((220, y), val, fill=(15, 23, 42))
        y += 45

    # Footer note
    draw.rectangle([(60, height - 90), (width - 60, height - 55)], fill=(241, 245, 249))
    draw.text((75, height - 80), "Retain this screenshot for dispute chargeback evidence.", fill=(71, 85, 105))

    img.save(SAMPLES_DIR / "upi-payment-receipt.png", "PNG")

    # 2. Logistics Delivery Slip
    slip = Image.new("RGB", (640, 700), color=(250, 250, 250))
    sdraw = ImageDraw.Draw(slip)
    sdraw.rectangle([(0, 0), (width, 90)], fill=(30, 41, 59))
    sdraw.text((30, 32), "E-Commerce Return & Delivery Proof Slip", fill=(255, 255, 255))

    sdraw.rectangle([(30, 120), (width - 30, 660)], fill=(255, 255, 255), outline=(203, 213, 225), width=2)
    sdraw.text((60, 150), "PARCEL DELIVERED TO MERCHANT WAREHOUSE", fill=(22, 101, 52))

    slip_fields = [
        ("Return AWB Tracking", "AWB-BLR-982019482"),
        ("Pickup City", "Bengaluru (Koramangala Hub)"),
        ("Destination Hub", "Mumbai Merchant Warehouse B-4"),
        ("Item Description", "Consumer Electronics (Invoice #INV-2026-89)"),
        ("Declared Value", "INR 2,500.00"),
        ("Delivery Timestamp", "26 August 2026, 11:20:00 IST"),
        ("Recipient Signature", "Verified by Store Incharge M. Rao"),
        ("Customer Refund Status", "Pending Merchant Credit Action"),
    ]
    sy = 200
    for l, v in slip_fields:
        sdraw.text((60, sy), l, fill=(100, 116, 139))
        sdraw.text((230, sy), v, fill=(15, 23, 42))
        sy += 48

    slip.save(SAMPLES_DIR / "delivery-confirmation-slip.png", "PNG")


def generate_xlsx_workbook() -> None:
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Dispute Settlement Log"

    headers = [
        "Dispute_ID",
        "Order_ID",
        "Payment_ID",
        "Transaction_Ref",
        "Claimed_Amount_INR",
        "Ledger_Refund_Amount_INR",
        "Ledger_Status",
        "City",
        "Payment_Rail",
        "Customer_Communication",
    ]
    ws.append(headers)

    # Style header row
    header_fill = PatternFill(start_color="1E293B", end_color="1E293B", fill_type="solid")
    header_font = Font(color="FFFFFF", bold=True)
    for col_idx in range(1, len(headers) + 1):
        cell = ws.cell(row=1, column=col_idx)
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center", vertical="center")

    rows = [
        (
            "DISP-2026-001",
            "ord_9201928",
            "pay_2500_ok",
            "RF-MH-02",
            2500.00,
            2500.00,
            "processed",
            "Mumbai",
            "Razorpay / UPI",
            "Your INR 2,500 refund was processed on 28 August.",
        ),
        (
            "DISP-2026-002",
            "ord_8492011",
            "pay_3200_disp",
            "RF-HI-01",
            3200.00,
            0.00,
            "none",
            "Bengaluru",
            "Razorpay / HDFC",
            "Aapka INR 3,200 refund kal process ho gaya tha to rahul@okhdfcbank.",
        ),
        (
            "DISP-2026-003",
            "ord_1029482",
            "pay_500_dev",
            "RF-DL-03",
            500.00,
            0.00,
            "none",
            "Delhi",
            "UPI / SBI",
            "कृपया मेरा 500 रुपये का रिफंड वापस करो।",
        ),
        (
            "DISP-2026-004",
            "ord_4920194",
            "pay_4999_rvw",
            "RF-HY-04",
            4999.00,
            0.00,
            "none",
            "Hyderabad",
            "Axis Bank",
            "Customer states double debit occurred during order checkout.",
        ),
    ]

    for r in rows:
        ws.append(r)

    # Adjust column widths
    for col in ws.columns:
        max_len = max(len(str(cell.value or "")) for cell in col)
        col_letter = col[0].column_letter
        ws.column_dimensions[col_letter].width = max(max_len + 3, 12)

    wb.save(SAMPLES_DIR / "merchant-reconciliation-sheet.xlsx")


def update_manifest_and_zip() -> None:
    manifest = {
        "title": "PRAMAAN Multi-Format Dispute Evidence Samples",
        "description": "Exemplary held-out and sandbox dispute evidence across CSV, PDF, PNG, XLSX, TXT, and JSON formats.",
        "version": "4.5.2",
        "formats_supported": ["csv", "pdf", "png", "jpg", "xlsx", "txt", "json"],
        "samples": [
            {
                "file": "dispute-ledger.csv",
                "format": "csv",
                "description": "Authoritative merchant payment and refund ledger export with 4 dispute transactions.",
            },
            {
                "file": "dispute-claims-batch.csv",
                "format": "csv",
                "description": "Batch dispute claims table with customer UPI VPAs, bank UTRs, and dispute codes.",
            },
            {
                "file": "chargeback-notice-RF01.pdf",
                "format": "pdf",
                "description": "Official merchant dispute notice for claim RF-HI-01 in PDF-1.4 format with customer text.",
            },
            {
                "file": "bank-settlement-receipt.pdf",
                "format": "pdf",
                "description": "Bank reconciliation confirmation certificate showing processed refund of INR 2,500.",
            },
            {
                "file": "upi-payment-receipt.png",
                "format": "png",
                "description": "Mobile banking UPI payment screenshot with Razorpay ID, UTR 492019284719, and amount.",
            },
            {
                "file": "delivery-confirmation-slip.png",
                "format": "png",
                "description": "Logistics delivery receipt for returned merchandise in Koramangala, Bengaluru.",
            },
            {
                "file": "merchant-reconciliation-sheet.xlsx",
                "format": "xlsx",
                "description": "Multi-column Excel spreadsheet workbook containing ledger dispute and settlement reconciliation.",
            },
            {
                "file": "customer-complaint-hinglish.txt",
                "format": "txt",
                "description": "Customer dispute email written in Hinglish dialect with INR 3,200 amount and UTR.",
            },
            {
                "file": "customer-complaint-hindi.txt",
                "format": "txt",
                "description": "Customer dispute message in Hindi Devanagari script with INR 500 verbal claim.",
            },
            {
                "file": "normal.json",
                "format": "json",
                "description": "Structured refund-not-processed matching ledger case yielding PASS.",
            },
            {
                "file": "hinglish.json",
                "format": "json",
                "description": "Hinglish customer dispute claim yielding safe REVIEW abstention.",
            },
            {
                "file": "contradiction.json",
                "format": "json",
                "description": "Contradictory customer communication yielding REVIEW.",
            },
            {
                "file": "adversarial.json",
                "format": "json",
                "description": "Prompt injection payload ignored by deterministic verifier yielding BLOCK.",
            },
            {
                "file": "missing-evidence.json",
                "format": "json",
                "description": "Incomplete structured state yielding safe REVIEW abstention.",
            },
            {
                "file": "ood.json",
                "format": "json",
                "description": "Out-of-scope dispute profile failing closed to REVIEW.",
            },
        ],
    }

    (SAMPLES_DIR / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    # Pack ALL files into carve-sample-bundles.zip
    zip_path = SAMPLES_DIR / "carve-sample-bundles.zip"
    all_sample_files = [
        "dispute-ledger.csv",
        "dispute-claims-batch.csv",
        "chargeback-notice-RF01.pdf",
        "bank-settlement-receipt.pdf",
        "upi-payment-receipt.png",
        "delivery-confirmation-slip.png",
        "merchant-reconciliation-sheet.xlsx",
        "customer-complaint-hinglish.txt",
        "customer-complaint-hindi.txt",
        "normal.json",
        "hinglish.json",
        "contradiction.json",
        "adversarial.json",
        "missing-evidence.json",
        "ood.json",
        "manifest.json",
    ]

    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as z:
        for fname in all_sample_files:
            file_path = SAMPLES_DIR / fname
            if file_path.exists():
                z.write(file_path, arcname=fname)

    print(f"Successfully generated {len(all_sample_files)} sample files and packed {zip_path}")


def main() -> None:
    print("Generating CSV samples...")
    generate_csv_samples()
    print("Generating TXT samples...")
    generate_txt_samples()
    print("Generating PDF samples...")
    generate_pdf_document(
        "chargeback-notice-RF01.pdf",
        "CHARGEBACK DISPUTE AUDIT NOTICE",
        "RF-HI-01",
        "Aapka INR 3,200 refund kal process ho gaya tha in Bengaluru via Razorpay",
        "3,200.00",
        "pay_3200_disp",
        "UTR: 492019284719 (HDFC Bank)",
        "Local Ledger Status: None (Unmatched)",
    )
    generate_pdf_document(
        "bank-settlement-receipt.pdf",
        "BANK RECONCILIATION SETTLEMENT CERTIFICATE",
        "RF-MH-02",
        "Your INR 2,500 refund was processed on 28 August",
        "2,500.00",
        "pay_2500_ok",
        "UTR: 892019284102 (SBI Bank)",
        "Local Ledger Status: Processed (Full Match)",
    )
    print("Generating PNG receipt images...")
    generate_png_receipts()
    print("Generating XLSX workbook...")
    generate_xlsx_workbook()
    print("Updating manifest and packing carve-sample-bundles.zip...")
    update_manifest_and_zip()


if __name__ == "__main__":
    main()
